### ISSUE TITLE
Add Callback function for when scrolling is complete

### ISSUE THREAD

**Issue by BrendanNeufeld** [Jam3/scroll-manager#1]
so something like:
`scoller.scrollTo(element, offsetToScroll, duration, ease, callback);`

You may want to format the `scrollTo` function to accept an options object and a callback function so you don't have to check for optional params. So something like:

```
var options = {
element: <some element>,
offsetToScroll: <offset>,
duration: <duration>,
ease: <ease>
}
scoller.scrollTo(options, callback);
```

This is up to you. But this format is pretty common and is easier to check for optional options and a callback.

**Comment by BrendanNeufeld** [comment]
I think you could add it here:
https://github.com/Jam3/scroll-manager/blob/master/index.js#L51

Something like:

```
if (elapsedTime < duration) {
              setTimeout(function() {
                  animateScroll(elapsedTime);
              }.bind(this), increment);
          }else{
            if(callback) callback();
          }
```

**Comment by mbfassnacht** [comment]
Thanks for the suggestion @BrendanNeufeld added in 1.1.0 :)
